### ISSUE TITLE
Firefox Support (or at least Safari)

### ISSUE THREAD

**Issue by sammcj** [igniterealtime/Pade#111]
Howdy,

I love the project and the idea to bring all these components together, however like many - I don't trust Google and don't use the Google Chrome (or somewhat unreliable Chromium) browser.

Would it be possible to add Firefox support for this?

If not, what about at least Safari?

Thanks so much :)

**Comment by deleolajide** [comment]
Technically, **yes**. The project is based on the the agreed browser extension standard which works on all browsers to various levels except **Safari**. The standard was originally created by the Chromium project and now available at various levels on the other browsers.

Personally, I have no motivation for this. Have been **bitten badly** by browser wars in the past. I have decided professionally to select my technology options and die or live by them. I don't do _least common factor_ user experiences any more and stopped using bloated software like jQuery on my new projects.

The beauty of making this an open project is that someone else someday could make that happen ;-)

>somewhat unreliable Chromium

Are you sure about this? 

Chrome is built by adding Google proprietary code on top of Chrome just as Pade adds unified communication features on top of Converse. If Chromium is unreliable, the Chrome would suffer the same fate.

**Comment by sammcj** [comment]
This has been debated to death but I'll state my opinion here just for clarification on my poorly chose use of wording, not to start a flame war - it's ok to disagree etc...:

Unreliable as a product, maybe not as software, e.g. Chormium doesn't self-update (you can rely on brew etc.. and make sure that's run every date), it can't run signed extensions (e.g. password managers of any quality) etc...

Chrome is built, configured and distributed by an Ad company, that makes up their own rules and standards for much of the internet - there's no way I'd run a browser from Google - with them YOU and your data are the product.

Firefox is built with open standards with a privacy and security first approach built by a not-for-profit.

**Comment by deleolajide** [comment]
>Unreliable as a product, maybe not as software, e.g. Chromium doesn't self-update

I don't think Chromium will ever be is a product. It is a software project. 

I have been a keen user of of Firefox since when it was known as Netscape. Mozilla have fostered a great open source web development community, but their technical choices at times leaves me very baffled.

I see Pàdé  mostly used by enterprise users and they **do not** standardize on Firefox. It used to be Internet Explorer and now it is Chrome.

**Comment by sammcj** [comment]
> and now it is Chrome.

Interesting, I didn't know that.

We've certainly standardised on Firefox, but still have Internet Explorer on the few Windows machines still used by managers - not that any of them use it.

These days Firefox offers Firefox for Enterprise (lol): https://www.mozilla.org/en-GB/firefox/enterprise/ and an ESR (LTS) release.

Several medium/large enterprise shops I know of actually ban or alert on the installation of Chrome due to either data leakage and tracking by Google or Google as a competitor for their products.

**Comment by deleolajide** [comment]
>These days Firefox offers Firefox for Enterprise

And I didn't know that. Thanks :-)

**Comment by marclaporte** [comment]
Pàdé is one of the many components of WikiSuite:
https://wikisuite.org/Software-Components

Jitsi Meet is another component. A few year years ago, Jitsi Meet didn't support Firefox and massive work was done in Jitsi Meet and Openfire Meetings to resolve this:
https://github.com/jitsi/jitsi-meet/issues/4#issuecomment-138425400
And now, it's not a lot of work to continue to support both.

So we all want Firefox support. Overall, it makes sense for Dele to focus on just one platform and continue to innovate at a rapid pace (Dele: you are awesome!). Other community members can port to Firefox as a way to learn, and support the project.

Openfire + Converse (XMPP) with Jitsi Meet (WebRTC) + Pàdé make a fantastic combo for the enterprise: https://wikisuite.org/Why-Openfire
It would be fantastic to combine with Firefox ESR, and not have major updates so frequently.

@sammcj: can you get involved? To more people help out, the more energy we have to port Pàdé to Firefox.

Thanks!

**Comment by sammcj** [comment]
@marclaporte happy to test any FF plugins and report back, but I'm contributing to too many Open Source projects at the moment I'm sorry - any more and I won't get anything finished hahaha 😂

**Comment by deleolajide** [comment]
Just tested Pàdé with Brave web browser based on Chromium, but developed by Brendan Eich, the inventor of JavaScript and co-founder of Mozilla.

So far, everything works ok with Brave running silently in the background as a run-time engine.

**Comment by ClaudeStabile** [comment]
@deleolajide  

We have tested with Firefox : loaded extension from zip : chat and all features works except vidconf. Vidconf does not work with latest ofmeet 0.95 but it is working with very old version 0.4.8, no clue why. I did many investgations to try to understand why but so far i am stuck. Probably related to p2p signaling for FF but...
You can check out with latest firefox old site https://webrtc.free-solutions.org OKI / new version https://www.free-solutions.org : KO Firefox experts could probably help us to pinpoint precisely where the problem is. 
On MS-WIN 10 + edge : We have tested Pade in PWA mode. Everything works perfectely(same as chrome) if you run edge > =74 release (Dev or maybe current now)
Safari & ios : i will ask some contacts and iphone users to test and report findings. If you have latest ios i would be please to hear some feedback.

I am now willing to test and help the project as much as i can for Firefox and safari. Working on any browser any platform would drastically help expanding/promoting Padé usage. I also fully understand that dele focus exclusively on chrome.
If this could help moving forward / help out testing and findings 
I have now several server instances running for test & experiments purpose and have the flexibility to perform quick changes for testing. Testers are welcomed, feel free to create your account and join on our servers .

https://www.free-solutions.org and pwa via https://www.free-solutions.org/pwa
You can contact me via my JID : claude@www.free-solutions.org or email claude@free-solutions.ch, i am willing to help on FF & safari supporting.

But so far my very BIG congrats to @deleolajide  and all contributors as current code is already working fine on many platforms and OS

**Comment by ClaudeStabile** [comment]
Hi everybody,

After a deep look and many tests with my servers, i have found the following reason for Firefox not working on my new Jitsi ofmeet instance.
When firefox is used, Stun server is never called, no trace of call in logs. With old realease of ofmeet, firefox is calling my stun server and it works. On latest ofmeet Firefox is never calling my STUN server so probably a STUN server calling when we use Firefox and latest ofmeet.

@deleolajide Can you please check if the is a reason why with firefox browser STUN server is not called ?
Many thanks in advance , hope this helps us fixing issues.

If you need to test on our servers, let me know

In my stinserver logs with chrome and old ofmeet i have that type of logs  and NONE with firefox and new ofmeet 

 20190604-111102.260 | reTurnServer | RETURN | 140479387571968 | StunMessage.cxx:82 | Successfully parsed StunMessage: STUN Request: Bind, id 42a412216d5f0cb8a0dd73213f245643
DEBUG | 20190604-111102.281 | reTurnServer | RETURN | 140479387571968 | StunMessage.cxx:82 | Successfully parsed StunMessage: STUN Request: Allocate, id 42a412214cc7b5d7734dadb84921d228
INFO | 20190604-111102.281 | reTurnServer | RETURN | 140479387571968 | RequestHandler.cxx:245 | Received Request with no Message Integrity. Sending 401. Sender=[UDP 46.126.175.40:57212]
DEBUG | 20190604-111102.343 | reTurnServer | RETURN | 140479387571968 | StunMessage.cxx:82 | Successfully parsed StunMessage: STUN Request: Allocate, id 42a41221f72ff868b6f38a83575ed076
WARNING | 20190604-111102.344 | reTurnServer | RETURN | 140479387571968 | RequestHandler.cxx:310 | MessageIntegrity is bad. Sending 401. Sender=[UDP 46.126.175.40:57212]
DEBUG | 20190604-111102.375 | reTurnServer | RETURN | 140479387571968 | StunMessage.cxx:82 | Successfully parsed StunMessage: STUN Request: Bind, id 42a41221f81e3b9b81eaae765fe8cdcb
DEBUG | 20190604-111102.375 | reTurnServer | RETURN | 140479387571968 | StunMessage.cxx:82 | Successfully parsed StunMessage: STUN Request: Allocate, id 42a41221a72c96e3c236fe8ecf8c721f
INFO | 20190604-111102.375 | reTurnServer | RETURN | 140479387571968 | RequestHandler.cxx:245 | Received Request with no Message Integrity. Sending 401. Sender=[UDP 46.126.175.40:45772]
DEBUG | 20190604-111102.401 | reTurnServer | RETURN | 140479387571968 | StunMessage.cxx:82 | Successfully parsed StunMessage: STUN Request: Allocate, id 42a4122116799dce4f0c9f956bb494b5
WARNING | 20190604-111102.401 | reTurnServer | RETURN | 140479387571968 | RequestHandler.cxx:310 | MessageIntegrity is bad. Sending 401. Sender=[UDP 46.126.175.40:45772]

Thanks in advance for all efforts made

**Comment by ClaudeStabile** [comment]
Another possible cause is Firefox locking webRTC cameras by default after FF 60
Problem might be related to this mozilla change see https://blog.mozilla.org/webrtc/better-privacy-on-camera-mute-in-firefox-60/  But no clue what to do to fix or test this.

**Comment by deleolajide** [comment]
Firefox support is now available in version 2.0

**Comment by alexanderadam** [comment]
@deleolajide sounds great! So is there a Firefox extension?

**Comment by deleolajide** [comment]
Yes. I have only done limited testing with it and I still have not figured out what is the equivalent of the chrome web store for Firefox and how to submit Firefox Add-Ons.

In general version 2.0 still has some show-stopping bugs that is preventing a release

**Comment by wrooot** [comment]
https://addons.mozilla.org/en-US/developers/

**Comment by alexanderadam** [comment]
Ah okay. So I guess the Firefox addons link will be added to the README then as well?

**Comment by ShroomiePerson** [comment]
uhh, how're things going on this front? i'm four or so years late so i have no clue what progress looks like.
