### ISSUE TITLE
Timeout for Chrome notification

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#150]
I'm using Pade on Windows 7 and it shows Chrome based notifications for messages. I wonder is it possible to have a timeout setting, so such notification would hide on its own.

**Comment by deleolajide** [comment]
I did have them auto-hide before and a user requested for them to be sticky and have a button to go direct to the chat or groupchat being notified. I will make it configurable with configurable timeout as well

**Comment by wrooot** [comment]
Maybe too complex, but could be a separate setting for mentions/interests to stick and for regular notifications to hide automatically.

**Comment by deleolajide** [comment]
Most notifications require an action and should really stick until user sees them and responds. They mostly occur when window is minimized (there is bug preventing this from working properly). The other type of notification happens with presence status notifications that just inform and timeout. 

With Windows 10, Macs and possible Linux, notifications are handled by O/S and auto-disappear if user interaction is not required. On Windows 10, they are moved into the notification panel for the user to view at leisure. 

You are right. There is no point adding any complex code just for Windows 7. I will fix the outstanding issue first to ensure the notification only happens when converse window minimized or not in focus and then revisit this issue.

**Comment by wrooot** [comment]
Yes, making it only show when window is not in focus might be enough. As for Windows 10, i need to test Pade with it to see how it actually works.

**Comment by deleolajide** [comment]
Done. Now available in version 1.1.5
