### ISSUE TITLE
Improve notification popup

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#157]
I don't know how hard (or is it possible at all) is to alter the popup i get in Chrome. But i would like to see:
* No Pade - Unified Communications at Work as a header as it takes too much space (maybe just leave Pade);
* Replace Pade icon with user's avatar if available (can still show this icon if no avatar is set, or maybe a generic avatar with first letter of a user);
* Show user's name before the message (maybe in bold). I really like to see who is saying what without opening a chat window just by looking at the popups.

I haven't yet looked into that, maybe i can even do something of these myself. Probably not :)

**Comment by deleolajide** [comment]
This what a notification looks like with Windows 10. We have limited control of what we can change or format. All Window applications use the same notification format.

![image](https://user-images.githubusercontent.com/110731/55760210-5bc60400-5a53-11e9-9351-14ad573a8725.png)

We can't change the header.  It is the extension name and short description and is taken automatically from the browser extension manifest file.

Icon is replaced with avatar for one2one chat. Groupchats don't have any avatars

We can't change the formatting of the username.

**Comment by deleolajide** [comment]
Improve notifications for group chat mentions. 

Show the nickname of the participant that mentions user's name and show avatar of that user if available

**Comment by deleolajide** [comment]
Done. Now available in version 1.2.3

![image](https://user-images.githubusercontent.com/110731/56039481-4b9c7600-5d2c-11e9-87d6-319dfa08b109.png)

**Comment by markra55** [comment]
extending on this, could you add notification numbering/dots on the group chats so that it's easy to see which group has an update?

This would be useful for contacts that are grouped as currently, I need to expand each group to find who has messaged me directly. if it was at a group level I can easily expand on the group.

Regards

Mark

![image](https://user-images.githubusercontent.com/49949301/56663211-72986780-669d-11e9-89b0-eaa8919fea14.png)
