### ISSUE TITLE
Xmpp account creation via Padé

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/Pade#165]
Is it possible to create accounts in  xmpp mode via Padé so it register directly in converse. ?

**Comment by deleolajide** [comment]
Registration is done via the Chat API plugin. Support is provided for email verification or directly with no email verification

**Comment by deleolajide** [comment]
If inbound account registration is checked in openfire, direct registration without any email checking is done. Otherwise, an email reply is expected from the provided email address to register the account.

![image](https://user-images.githubusercontent.com/110731/56825990-39a5f180-685b-11e9-8568-525f99c3bcf9.png)

Registration via chat api plugin is more elaborate that standard xmpp  in-band registration. Default shared roster groups, groupchat rooms and bookmarks are created automatically.
