### ISSUE TITLE
Can't insert images at igniterealtime.org

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#187]
Using Pade for Work. Usually i could just Ctrl-V into group chat to paste an image, now it doesn't work and i can't find a button to do this manually.

**Comment by deleolajide** [comment]
There are 2 possible issues that cause this to happen.

1. httpfileupload plugin does not respond to service discovery requests and converse disables uploading. When that happens, the upload icon disappears from the toolbar.

2. converse has a bug that causes the httpfileupload  service discovery to fail from race conditions at startup when opening bookmarked rooms. This bug is not consistent and does not not happen all the time for all rooms.

Workaround is to close room and re-open or avoid auto-join rooms. If the icon still does not happen after a re-open, the you are looking at issue no1 and you would need to reload the openfire httpfileupload plugin as it sometimes fails after long periods of usage

**Comment by wrooot** [comment]
I was able to upload with Spark at that time though

**Comment by deleolajide** [comment]
That means it was the converse issue no2 that was in effect

**Comment by wrooot** [comment]
I tried to restart Pade. I have this room on auto join

**Comment by deleolajide** [comment]
Restart does not work as the same thing can happen again at startup. Just leave the room and rejoin or use the refresh button

![image](https://user-images.githubusercontent.com/110731/59423189-92105e80-8dc9-11e9-936a-c833248d4841.png)

![image](https://user-images.githubusercontent.com/110731/59423213-9d638a00-8dc9-11e9-8fad-a56571380ee7.png)

The refresh button is the simplest. It is a leave and rejoin action
