### ISSUE TITLE
Contact showing as pending in Pade

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/Pade#188]
For some reason one contact is shown as pending in Pade. Looks ok in Spark or Gajim.
![image](https://user-images.githubusercontent.com/7195609/59704802-aeffc400-9205-11e9-83c2-1c4e2fedfe15.png)

**Comment by deleolajide** [comment]
Sometimes and somehow, Converse misses the subscribe presence stanza to complete presence subscription. When that happens, the contact gets stuck in pending never-ever-land. I have one on my roster right now as well.

It is possible that the stanza is not sent to all instances, but I would need to debug to confirm that or otherwise. Thanks for raising the issue.

**Comment by wrooot** [comment]
Btw, i have added alameyo long time ago and he was appearing in approved contacts. I noticed this pending issue only yesterday.

**Comment by deleolajide** [comment]
It is possible he may have lost and recreated his contacts?

**Comment by wrooot** [comment]
Maybe. @alameyo ?

**Comment by wrooot** [comment]
He says he has reinvited me.

**Comment by deleolajide** [comment]
I suspect Spark may have swallowed it and converse is still waiting for it even though the contact is fully subscribed on the roster in Openfire. It could be a cache problem and you may have to do a factory reset to reset the converse roster cache. 

Try the roster refresh button first :-)

**Comment by wrooot** [comment]
I have tried to remove him and add again. It showed up as pending in converse. After he has approved me, it started showing as online in Spark. Still was showing as pending in converse. After pressing refresh in converse it appeared as online. I tried pressing refresh first, but it didn't do anything, so had to remove and readd.
