### ISSUE TITLE
Couple quick questions

### ISSUE THREAD

**Issue by bmccorkle** [igniterealtime/pade#218]
As I get used to Pade coming from Spark, I noticed a couple things I've missed from Spark.

Get Users Attention:   Is this possible in Pade?  I'm guessing not since it is browser oriented but it was nice to be able to shake the window when you knew the other user was involved in something else on the PC.

Contact list on the side.  This is a bigger deal to me.  We have lots of contact in our list and I've noticed that you can't scroll down the list to view the contacts but have to filter for them (unless I'm missing something).   Is there a way to scroll down in the list?

**Comment by deleolajide** [comment]
> Get Users Attention: Is this possible in Pade?

I use desktop notifications to get attention. In groupchat, I use mentions (@nickname) in a message. In normal chat, I just type any message. 

If Pade window is minimized or not in focus, the user gets a desktop notification like this
![image](https://user-images.githubusercontent.com/110731/78791719-24f93580-79a8-11ea-8e0e-7c2bc2beb2d3.png)

Also the pade icon on the windows toolbar flashes like this

![image](https://user-images.githubusercontent.com/110731/78792086-9933d900-79a8-11ea-8350-6b353dc9df60.png)

> I've noticed that you can't scroll down the list to view the contacts

You can, you use the scroll wheel of the mouse. The scroll bar is missing because of space. 

![image](https://user-images.githubusercontent.com/110731/78792602-3989fd80-79a9-11ea-9e09-249e2ad2965a.png)

Most of the time, I am only interested in my active conversations. I switch view to the active conversations list

![image](https://user-images.githubusercontent.com/110731/78792992-c0d77100-79a9-11ea-93b2-da5450252b8f.png)

**Comment by deleolajide** [comment]
There is also a directory search tool using the two people icon on the toolbar to search for contacts and use to open a chat or invite them to the opened/active groupchat

![image](https://user-images.githubusercontent.com/110731/78794653-efeee200-79ab-11ea-82bc-211ebcbcf69b.png)
