### ISSUE TITLE
Integrate Pàdé with existing Jitsi-meet server

### ISSUE THREAD

**Issue by cohiba274** [igniterealtime/pade#221]
Hi,

That would be fantastic if we had the choice to use our own Jitsi-meet server instead of meet.jit.si

**Comment by deleolajide** [comment]
Thank you for reporting this.  https://deleolajide.github.io/pade/ has now been upgraded from 1.6.2 to 1.6.8.

In order to use your own jitsi-meet server, you would need to install [Openfire Pade plugins (pade.jar, ofmeet.jar and offocus.jar)](https://github.com/igniterealtime/openfire-pade-plugin)  on your openfire server.
