### ISSUE TITLE
SVG version of the Pade logo

### ISSUE THREAD

**Issue by sjehuda** [igniterealtime/pade#270]
Good day!

I would be glad to obtain an SVG version of the Pade logo, in order to include it in the list of recommended XMPP client of FASI (an HTML invite page for XMPP.

See https://git.xmpp-it.net/sch/FASI/issues/1

**Comment by deleolajide** [comment]
Hi Schimon 🙂

Thanks for doing this. Here is the svg file as requested

-dele
________________________________
From: Schimon Jehuda ***@***.***>
Sent: Sunday, October 20, 2024 10:28 AM
To: igniterealtime/pade ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [igniterealtime/pade] SVG version of the Pade logo (Issue #270)


Good day!

I would be glad to obtain an SVG version of the Pade logo, in order to include it in the list of recommended XMPP client of FASI (an HTML invite page for XMPP.

See https://git.xmpp-it.net/sch/FASI/issues/1

**Comment by sjehuda** [comment]
dele, GH does not support email attachments, which is another reason of
why I do not use it.

Could you please send it to me at "open_chat".

Thank you,
Schimon

**Comment by deleolajide** [comment]
https://igniterealtime.github.io/pade/pade.svg

Here is a direct link 🙂
________________________________

**Comment by sjehuda** [comment]
This is how it currently appears.

Please. Inform me, if you want to add more links to the "Details" section, or to modify the description.

![scrot-rofi_20241028-075137](https://github.com/user-attachments/assets/0f458d6f-987f-4db8-b15d-20ad5e02171e)

```

[pade]
title = "Pàdé"
about = """
Browser Extension based XMPP unified communications client

Pàdé is the Yoruba word for "Meet". It is a unified real-time collaboration \
client optimized for business and organizations implemented as a cross-\
platform browser extension.
"""
browser = "https://igniterealtime.org/projects/pade/"
properties = ["chat", "desktop", "extension", "graphical", "mobile", "omemo"]
resources = [
    { url = "https://igniterealtime.org/projects/pade/", txt = "Project homepage" },
]

```
