### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by enlicayomer** [igniterealtime/Pade#4]
hi, when I install the extension, the built-in ofmeet plugin is not affected and opens a new window instead. What is the reason of this ? So, is it possible to do screen sharing from 
_https://<server-name>:7443/ofmeet/room-name_  ?

**Comment by deleolajide** [comment]
No,  can't use it for screen-share with a web page. You need to create your own chrome extension with permissions for your own domain xyz.com before you can do screen share with https://xyz.com:7443/ofmeet/room-name.

This is due because webrtc screen-share with chrome from Jitsi Meet requires a custom extension based on individual user domains see https://github.com/jitsi/jidesha1 for more details

Pàdé  is no more a screen share chrome extension, but a fully working client and does screen-share from any domain because Jitsi Meet is built-in and trusted and does not require permissions.

**Comment by enlicayomer** [comment]
Thank you. I already have a chat application that I want to do video and audio conversations like whatsApp is also. Which technologies/plugins do you recommend for this? Also I want to do remote control, I want to work on this. Your ideas are important to me.
