### ISSUE TITLE
Support more than one XMPP account

### ISSUE THREAD

**Issue by marclaporte** [igniterealtime/Pade#74]
As Pàdé gains features, more will use it, and some will have more than one XMPP account. Ex.: one for work, and a personal account.

**Comment by deleolajide** [comment]
Thanks for raising this issue. I have thought hard and long about this. I have my personal views about this as the implementations in Jitsi and Conversations are as complicated as using SMS with a mobile phone that has 2 SIM cards.

XMPP federation by design should allow a user to access both work related and personal chat-rooms/contacts with a single account. However there may be business rules that may mandate the separation of contacts and enforcing of different communication regulations.

The traditional way was to use an XMPP gateway server-side and once upon a time, Kraken was the most popular Openfire plugin because its multiple tentacles enabled bridging into AIM, Yahoo, GTalk and multiple XMPP accounts.

I am in favor of doing it server-side with simpler version of Kraken that does only XMPP accounts instead of a client-side implementation in the style of JItsi or Conversations. It will be simpler to add a plugin to Converse to manage the [XMPP gateway protocol known as XEP 0100](https://xmpp.org/extensions/xep-0100.html)

However, there is simpler solution if the requirement is just to have work and personal accounts. This is the approach adopted by WhatsApp. The creation of the WhatsApp Business application which is basically a clone of WhatsApp with some new unique business related features. As Pade was designed to clone-able with the intent to re-brand for different use cases, I can easily add Pàdé for Business to the Chrome Web Store.

**Comment by deleolajide** [comment]
Pàdé at work cloned and available from chrome web store as from version 0.6.0.  Both applications have been re-branded with new icons.

![image](https://user-images.githubusercontent.com/110731/46800455-a0483f80-cd4f-11e8-9f31-a0ed71c6bb54.png)

Converse@Home

![image](https://user-images.githubusercontent.com/110731/46800610-22386880-cd50-11e8-991a-63afc52fcc31.png)

Converse@Work

![image](https://user-images.githubusercontent.com/110731/46800708-75aab680-cd50-11e8-92e1-82cb1260e07d.png)

**Comment by marclaporte** [comment]
I see what you mean by UX challenges in XMPP clients. I have 4 XMPP accounts myself. And it's tricky when contacts get mixed up. So I an intrigued with the idea of starting two instances of Pàdé 

Is multiple instances of a Chrome Extension supported?
Will that fragment our work / community here? 
https://chrome.google.com/webstore/detail/pade-openfire-meetings/fohfnhgabmicpkjcpjpjongpijcffaba?hl=en

In the future, when we support other browsers, one could get yet more XMPP accounts supported. 2 via Firefox, 2 via Chromium, etc. ;-)

Thanks!

**Comment by deleolajide** [comment]
>Is multiple instances of a Chrome Extension supported?

No. Not that I am aware of. It will be Pade packaged as Pade@Home and Pade@Work in the chrome web store.

Long term solution for multiple accounts will be to use an XMPP gateway as explained earlier on.

**Comment by deleolajide** [comment]
[Pade@Work](https://chrome.google.com/webstore/detail/pade-unified-communicatio/aeoodbenjbanpkchnjcpamplolonakpo/) (formerly known as Pade) now available from chrome web store
[Pade@Home](https://chrome.google.com/webstore/detail/pade-unified-communicatio/aeoodbenjbanpkchnjcpamplolonakpo) is also available from chrome web store

**Comment by marclaporte** [comment]
Both URLs are identical

**Comment by deleolajide** [comment]
>Both URLs are identical

Thanks, Just corrected it :-)
