### ISSUE TITLE
Break-out rooms

### ISSUE THREAD

**Issue by marclaporte** [igniterealtime/Pade#85]
https://support.zoom.us/hc/en-us/articles/206476093-Getting-Started-with-Breakout-Rooms
https://bigbluebutton.org/2017/01/12/1-1-beta/

**Comment by deleolajide** [comment]
Looks like something that can be done with a custom Converse plugin. 

It can be implemented with XMPP groupchat  and groupchat invitations. It would need a UI for the breakout coordinator to manage the break-out rooms, participant assignment and room monitoring.

Sounds like a good task for TeamDRC

**Comment by deleolajide** [comment]
I forgot to mention. There is already the ability to search and create a meeting invitation list in Pade. THis can easily be extended for breakout rooms

![image](https://user-images.githubusercontent.com/110731/47683465-8c159680-dbc7-11e8-9e23-86bad96bfab5.png)

**Comment by deleolajide** [comment]
I have an outstanding TODO to implement a client side version of Meeting planner as currently available in the Openfire Meetings plugin for Openfire. In order to do that, I have to be able to save  and recall Meeting Invitations.  This is now available in Pade version 0.7.3

First you search and build a list of participants and then save them by clicking on "Meet Later".

![image](https://user-images.githubusercontent.com/110731/47734723-cc762280-dc62-11e8-94d8-59b01de36ed3.png)

Then you can recall them later for  re-inviting the same people to a meeting or rejoin the meeting if you dropped out.

![image](https://user-images.githubusercontent.com/110731/47734943-545c2c80-dc63-11e8-8044-0035bbed7bd0.png)

![image](https://user-images.githubusercontent.com/110731/47735001-72c22800-dc63-11e8-8064-deac4e705594.png)

This is not a fully featured **break-out rooms** implementation, but quite usable when combined with Converse
